### ISSUE TITLE
PiggyCustomEnchants support pls

### ISSUE THREAD

**Issue by UnEnanoMas** [Ree-jp-minecraft/StackStrage#10]
Pls i need help whit this:

```
07.05 15:00:58 [Server] Server thread/ERROR >> StackStorage error
07.05 15:00:58 [Server] Server thread/ERROR >> Details : enchant not found/plugins/StackStrage-master/src/ree_jp/stackStorage/sqlite/StackStorageHelper.php213
```
For some strange reason it stopped working for some users but it worked correctly before.

I think it is due to the enchantments of piggycustomenchants, please my users have disappeared the objects for those enchantments

**Comment by Ree-jp** [comment]
Please download the corresponding one from here
https://poggit.pmmp.io/ci/Ree-jp-minecraft/StackStrage/
