### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Sulfuritium** [Ree-jp-minecraft/StackStrage#13]
Hello,

I wanted to use your plugin in YAML version but as soon as I took an item in my inventory, the server crashed: /

Crash: https://crash.pmmp.io/view/5157510

**Comment by Ree-jp** [comment]
Sorry for delay
The yaml version is for your own server and cannot be used
Also, the yaml version has a bug that causes items to multiply.

**Comment by Ree-jp** [comment]
Try using the sqlite version currently published on poggit

**Comment by SPMP2** [comment]
Work? I used 0.7.0 this dev work?
