### ISSUE TITLE
Not loaded

### ISSUE THREAD

**Issue by SPMP2** [Ree-jp-minecraft/StackStrage#15]
223 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: ree_jp\stackStorage\libs\poggit\libasynql\ConfigException: "Config problem: Database settings are missing or incorrect" (EXCEPTION) in "plugins/StackStrage.phar/src/ree_jp/stackStorage/libs/poggit/libasynql/libasynql" at line 77
224 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #0 plugins/StackStrage.phar/src/ree_jp/stackStorage/sql/StackStorageHelper(29): ree_jp\stackStorage\libs\poggit\libasynql\libasynql::create(object ree_jp\StackStorage\StackStoragePlugin, boolean , array[2])
225 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #1 plugins/StackStrage.phar/src/ree_jp/stackStorage/StackStoragePlugin(30): ree_jp\stackStorage\sql\StackStorageHelper->__construct(object ree_jp\StackStorage\StackStoragePlugin, string[76] /home/gameserver/servers/serveur7/minecraftbedrock/plugin_data/StackStorage/)
226 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/PluginBase(116): ree_jp\StackStorage\StackStoragePlugin->onEnable()
227 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
228 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
229 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
230 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
231 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
232 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
233 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #9 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)
  | 1 line
235 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: Error: "Typed static property ree_jp\stackStorage\sql\StackStorageHelper::$instance must not be accessed before initialization" (EXCEPTION) in "plugins/StackStrage.phar/src/ree_jp/stackStorage/StackStoragePlugin" at line 52
236 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/plugin/PluginBase(118): ree_jp\StackStorage\StackStoragePlugin->onDisable()
237 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/PluginManager(639): pocketmine\plugin\PluginBase->setEnabled(boolean )
238 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/PluginManager(559): pocketmine\plugin\PluginManager->disablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
239 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
240 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
241 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
242 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
243 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
244 | 2021-09-14 [00:21:24] [Server thread/CRITICAL]: #8 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)

**Comment by Ree-jp** [comment]
Did you set up sql.yml correctly?
https://poggit.pmmp.io/p/StackStorage/1.0.1#rdesc-section-config

**Comment by Ree-jp** [comment]
I'm sorry
I made a typo with sql.yaml in sql.yml
Rename the file to sql.yml and try again

**Comment by SPMP2** [comment]
Don’t work i don’t understand i must place
database:
  # mysql or sqlite
  type: mysql

    # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
  # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: StackStorage
    password: password
    # Database name
    schema: StackStorage
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 2
In sql.yml

**Comment by SPMP2** [comment]
Bro i don’t understand your plugin doesn’t work but v0.7.0 work but i have lots of bugs i want to download 1.0.1 but not loaded

**Comment by SPMP2** [comment]
Can you send me a valid config please !

**Comment by SPMP2** [comment]
2021-09-25 [14:37:08] [Server thread/CRITICAL]: ree_jp\stackStorage\libs\poggit\libasynql\SqlError: "SQL CONNECT error: Connection refused" (EXCEPTION) in "plugins/StackStrage.phar/src/ree_jp/stackStorage/libs/poggit/libasynql/libasynql" at line 141
--
182 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #0 plugins/StackStrage.phar/src/ree_jp/stackStorage/sql/StackStorageHelper(27): ree_jp\stackStorage\libs\poggit\libasynql\libasynql::create(string[46] object(ree_jp\StackStorage\StackStoragePlugin), array[4], array[2])
183 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #1 plugins/StackStrage.phar/src/ree_jp/stackStorage/StackStoragePlugin(30): ree_jp\stackStorage\sql\StackStorageHelper->__construct(string[46] object(ree_jp\StackStorage\StackStoragePlugin), string[76] /home/gameserver/servers/serveur7/minecraftbedrock/plugin_data/StackStorage/)
184 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/PluginBase(116): ree_jp\StackStorage\StackStoragePlugin->onEnable()
185 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
186 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(string[46] object(ree_jp\StackStorage\StackStoragePlugin))
187 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(string[46] object(ree_jp\StackStorage\StackStoragePlugin))
188 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
189 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(string[23] object(BaseClassLoader), string[35] object(pocketmine\utils\MainLogger), string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
190 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
191 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #9 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)
  | 1 line
193 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: Error: "Typed static property ree_jp\stackStorage\sql\StackStorageHelper::$instance must not be accessed before initialization" (EXCEPTION) in "plugins/StackStrage.phar/src/ree_jp/stackStorage/StackStoragePlugin" at line 52
194 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/plugin/PluginBase(118): ree_jp\StackStorage\StackStoragePlugin->onDisable()
195 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/PluginManager(639): pocketmine\plugin\PluginBase->setEnabled(boolean )
196 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/PluginManager(559): pocketmine\plugin\PluginManager->disablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
197 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
198 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object ree_jp\StackStorage\StackStoragePlugin)
199 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
200 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
201 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
202 | 2021-09-25 [14:37:08] [Server thread/CRITICAL]: #8 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)

**Comment by Ree-jp** [comment]
[sql.zip](https://github.com/Ree-jp-minecraft/StackStrage/files/7229733/sql.zip)
Show me your sql.yml

**Comment by SPMP2** [comment]
Thank’s i will try, 
My sql :
first try: 

--- []
...

second try: 

--- 
database:
  # mysql or sqlite
  type: mysql

    # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
  # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: StackStorage
    password: password
    # Database name
    schema: StackStorage
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 2
...

**Comment by SPMP2** [comment]
This working with your config !! You can place your config in src i think .. ?

**Comment by SPMP2** [comment]
Bro i don’t understand why stackstorage don’t open the storage but create double chest on top of my player it’s according to my position because in certain place, stack storage work ……

**Comment by SPMP2** [comment]
2021-09-25 [15:06:04] [Server thread/CRITICAL]: InvalidStateException: "No free window IDs found" (EXCEPTION) in "pmsrc/src/pocketmine/Player" at line 4108
--
261 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #0 plugins/StackStrage.phar/src/ree_jp/stackStorage/api/GuiAPI(40): pocketmine\Player->addWindow(object ree_jp\stackStorage\virtual\VirtualStackStorage)
262 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #1 plugins/StackStrage.phar/src/ree_jp/stackStorage/gui/StackStorage(50): ree_jp\stackStorage\api\GuiAPI->sendGui(string[7] MadoxMc, object ree_jp\stackStorage\virtual\VirtualStackStorage)
263 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/scheduler/ClosureTask(61): ree_jp\stackStorage\gui\StackStorage->ree_jp\stackStorage\gui\{closure}(integer 14306)
264 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/scheduler/TaskHandler(137): pocketmine\scheduler\ClosureTask->onRun(integer 14306)
265 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 14306)
266 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 14306)
267 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/Server(2389): pocketmine\plugin\PluginManager->tickSchedulers(integer 14306)
268 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
269 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
270 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
271 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
272 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
273 | 2021-09-25 [15:06:04] [Server thread/CRITICAL]: #12 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)
274 | 2021-09-25 [15:06:04] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
275 | 2021-09-25 [15:06:04] [Server thread/EMERGENCY]: Please upload the "/home/gameserver/servers/serveur7/minecraftbedrock/crashdumps/Sat_Sep_25-15.06.04-CEST_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
276 | 2021-09-25 [15:06:05] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/5234170 or use the ID #5234170.

**Comment by Ree-jp** [comment]
Does that mean I can't open the storage with the slapper plugin?
I'm using machine translation so I can't understand it well

**Comment by SPMP2** [comment]
I used /slapper edit addcommand rca {player} stackstorage 
But i will say you, the stackstorage command don’t working everywhere, i can’t open stackstorage where i want, sometimes i must be 15x the command stackstorage to open the storage, i cant make a video or you can join my server and try the command, just double chest creating on top of my player but storage doesn’t work

**Comment by Ree-jp** [comment]
To open someone else's storage / stackstorage [xuid]
Please run the
If the person is online you can open it by name
/ stackstorage [name]

**Comment by SPMP2** [comment]
No, i tell you, when y do /stackstorage, the storage don’t open, my storage don’t open but double chest is created on top of my head !

**Comment by SPMP2** [comment]
https://youtu.be/G6PS0TScPgc

**Comment by Ree-jp** [comment]
It may be due to the processing speed of the server
I created a trial with the delay of opening the storage 7 times longer than usual
try it
https://poggit.pmmp.io/r/143057/StackStrage_dev-39.phar

**Comment by SPMP2** [comment]
Okok thank you i will try now !! And if you want more of this bug i have do another video https://youtu.be/EmvvNAO04AU

**Comment by SPMP2** [comment]
Same issue with dev 39 i think it’s with position of player but it’s not sure

**Comment by Ree-jp** [comment]
The location is not important as the chest is set up to deceive the client
I think the problem is that the chest doesn't become a large chest
Chests are usually connected like this
https://youtu.be/yHcnf3_AKFw

**Comment by SPMP2** [comment]
Ooh okok i see !! But why my chest doesn’t become a large chest 🤔 it’s maybe an other plugin ?

**Comment by Ree-jp** [comment]
is that so
Try disabling other plugins once

**Comment by SPMP2** [comment]
Okok i will try without plugin
