### ISSUE TITLE
 API to get the number of items in the stack storage or please add simple api document

### ISSUE THREAD

**Issue by DaisukeDaisuke** [Ree-jp-minecraft/StackStrage#16]
Currently, it is difficult to get the number of items in the stack storage.
Therefore, can you add the following api or something similar?
```php
StackStorageAPI::getCount();
```

<details>
<summary>日本語 - Japanese</summary>
<br />

> スタックストレージ内に存在するアイテム数を取得するAPI、または簡単なapiドキュメントを追加していただく事は可能でしょうか...?

現在、スタックストレージ内のアイテム状況を取得する事に関しては、困難です。
つきましては、以下のapi等を追加していただく事は可能でしょうか...?
```php
StackStorageAPI::getCount();
```
</details>

**Comment by Ree-jp** [comment]
- 指定したアイテムの数を取得する
- すべてのアイテムを取得する
のapiの実装を検討します
closureで結果を使用する仕組みになる予定です

**Comment by DaisukeDaisuke** [comment]
ありがとうございます！
