### ISSUE TITLE
Maybe world ?

### ISSUE THREAD

**Issue by SPMP2** [Ree-jp-minecraft/StackStrage#18]
I have try in other world, my world  and in my other world (converted java world)  this working in normal world but the bug is in world converted https://youtu.be/Sj93X-jBhNk

**Comment by Ree-jp** [comment]
The world converted from java had a problem that chests could not be connected.
I can't fix that problem, but I'm thinking of an alternative to having one chest instead of a large one.

**Comment by Ree-jp** [comment]
This version uses only one chest
I think this will open
https://poggit.pmmp.io/r/143073/StackStrage_dev-41.phar

**Comment by SPMP2** [comment]
Really nice thank you very mutch bro !!!
