### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SPMP2** [Ree-jp-minecraft/StackStrage#19]
Hi bro, i have the same problem with one chest i have one chest on top of my player, i can’t open the storage on Converted World but i can in pocketmine world….

**Comment by Ree-jp** [comment]
Fixed
Thank you for reporting
https://poggit.pmmp.io/p/StackStorage/1.1.3

**Comment by SPMP2** [comment]
Wow bro very NICE JOB thank's for your great Plugin
