### ISSUE TITLE
スタックストレージ内のアイテムを素早く移動/連打する事による、アイテム増殖バグ

### ISSUE THREAD

**Issue by DaisukeDaisuke** [Ree-jp-minecraft/StackStrage#21]
## 素早いアイテム移動による増殖バグ
再現手順
- スタックストレージに64個(128個)未満のアイテムを格納します。
- 素早く、複数回にわたり、アイテムを別スロットに移動します。
- 一時的ではないアイテムの増殖を確認します。
https://youtu.be/GRLxcjIlbn8
## アイテムの連打による増殖バグ
再現手順
(おそらく、インベントリトランザクション失敗によるバグだと思います...)
- スタックストレージに64個(128個)未満のアイテムを格納します
- 素早くアイテムを連打します。
- インベントリトランザクション関連のログ表示、一時的ではないアイテムの増殖を確認します。
```
 Actions: [{"sourceType":0,"windowId":124,"sourceFlags":0,"inventorySlot":0,"oldItem":{},"newItem":{}},{"sourceType":0,"windowId":25,"sourceFlags":0,"inventorySlot":0,"oldItem":{},"newItem":{}}]
```
https://youtu.be/PMl-JkInNHw

**Comment by Ree-jp** [comment]
報告ありがとうございます
クリエイティブモードの時のみインベントリトランザクションが失敗してもpmmp側が無視するため発生するバグで、サバイバルやアドベンチャー、スペクテイターモードの際はpmmp側が対処してくれるため、問題ないと思われます
https://youtu.be/XoNdSkadwB8
